sonar.projectKey=23deFevereiro_API_5_SEM_BACK
sonar.organization=23defevereiro-1


sonar.sources=API_5_SEM_BACK

sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**

sonar.python.coverage.reportPaths=API_5_SEM_BACK/coverage.xml
sonar.coverage.exclusions=**/migrations/**,**/tests/**
