sonar.projectKey=23deFevereiro_API_5_SEM_BACK
sonar.organization=23defevereiro-1
sonar.host.url=https://sonarcloud.io

sonar.sources=.

sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/migrations/**,**/tests/**
sonar.cpd.exclusions=**/tests/**
