sonar.projectKey=23deFevereiro_API_5_SEM_BACK
sonar.organization=23defevereiro-1

sonar.host.url=https://sonarcloud.io

sonar.sources=.

sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**,**/.github/workflows/**
sonar.cpd.exclusions=**/tests/**,**/models/**
sonar.coverage.exclusions=**/migrations/**,**/tests/**,**/scripts/**,**/management/**,**/conftest.py,api/settings.py,api/urls.py,api/wsgi.py,api/asgi.py,manage.py
sonar.issue.ignore.multicriteria=settings-secret-key,settings-debug
sonar.issue.ignore.multicriteria.settings-secret-key.ruleKey=python:S2068
sonar.issue.ignore.multicriteria.settings-secret-key.resourceKey=api/settings.py
sonar.issue.ignore.multicriteria.settings-debug.ruleKey=python:S4507
sonar.issue.ignore.multicriteria.settings-debug.resourceKey=api/settings.py
