# Generated by Django 6.0.3 on 2026-05-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_dimprojeto_data_fim_prevista_dimprojeto_data_inicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimfornecedor",
            name="razao_social",
            field=models.CharField(max_length=120),
        ),
    ]
